import localFont from "next/font/local";
import "./globals.css";
import LoginBtn from "./LoginBtn";
import { getServerSession } from "next-auth";
import { authOptions } from "@/pages/api/auth/[...nextauth]";
import LogoutBtn from "./LogoutBtn";
import { cookies } from "next/headers";
import DarkMode from "./DarkMode";

const geistSans = localFont({
  src: "./fonts/GeistVF.woff",
  variable: "--font-geist-sans",
  weight: "100 900",
});
const geistMono = localFont({
  src: "./fonts/GeistMonoVF.woff",
  variable: "--font-geist-mono",
  weight: "100 900",
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default async function RootLayout({ children }) {
  let session = await getServerSession(authOptions);
  let cookie = cookies().get("name");
  return (
    <html lang="en">
      <body
        className={
          cookie != undefined && cookie.value == "dark" ? "dark-mode" : ""
        }
      >
        <div className="navbar">
          <span>yoon post</span>
          {session ? (
            <span className="name">
              {session.user.name} <LogoutBtn />
            </span>
          ) : (
            <LoginBtn />
          )}
          <DarkMode></DarkMode>
        </div>
        {children}
      </body>
    </html>
  );
}
