import type { Metadata } from "next";
import Link from "next/link";
import "./globals.css";

import LoginBtn from "@/components/LoginBtn";
import LogoutBtn from "@/components/LogoutBtn";
import { getServerSession } from "next-auth";
import { authOptions } from "@/pages/api/auth/[...nextauth]";
import ButtonLink from "@/components/ButtonLink";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  let session = await getServerSession(authOptions);

  return (
    <html lang="en">
      <body>
        <div className="navbar">
          <div>
            <Link href="/" className="logo">
              Forum
            </Link>
            <Link href="/list">List</Link>
            <Link href="/write">Write</Link>
          </div>
          {session?.user?.name ? (
            <div>
              {session.user.name}
              <LogoutBtn />
            </div>
          ) : (
            <div>
              <ButtonLink url="/register" label="register" />
              <LoginBtn />
            </div>
          )}
        </div>
        {children}
      </body>
    </html>
  );
}
