import type { Metadata } from "next";
import Link from "next/link";
import "./globals.css";

import LoginBtn from "@/components/LoginBtn";
import LogoutBtn from "@/components/LogoutBtn";
import { getServerSession } from "next-auth";
import { authOptions } from "@/pages/api/auth/[...nextauth]";
import ButtonLink from "@/components/ButtonLink";
import DarkMode from "@/components/DarkMode";
import { cookies } from "next/headers";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  let session = await getServerSession(authOptions);

  let mode = cookies().get("mode")?.value;

  return (
    <html lang="en">
      <body className={mode == "dark" ? "dark-mode" : ""}>
        <div className="navbar">
          <div>
            <Link href="/" className="logo">
              Forum
            </Link>
            <Link href="/list">List</Link>
            <Link href="/write">Write</Link>
          </div>
          <div>
            {session?.user?.name ? (
              <>
                {session.user.name}
                <LogoutBtn />
              </>
            ) : (
              <>
                <ButtonLink url="/register" label="register" />
                <LoginBtn />
              </>
            )}
            <DarkMode />
          </div>
        </div>
        {children}
      </body>
    </html>
  );
}
