import localFont from "next/font/local";
import "./globals.css";
import Link from "next/link";
import LoginBtn from "./LoginBtn";
import { getServerSession } from "next-auth";
import { authOptions } from "@/pages/api/auth/[...nextauth]";
import LogoutBtn from "./LogoutBtn";
import SignupBtn from "./SignupBtn";

const geistSans = localFont({
    src: "./fonts/GeistVF.woff",
    variable: "--font-geist-sans",
    weight: "100 900",
});
const geistMono = localFont({
    src: "./fonts/GeistMonoVF.woff",
    variable: "--font-geist-mono",
    weight: "100 900",
});

export const metadata = {
    title: "Create Next App",
    description: "Generated by create next app",
};

export default async function RootLayout({ children }) {
    let session = await getServerSession(authOptions);
    console.log(session);
    return (
        <html lang="en">
            <body className={`${geistSans.variable} ${geistMono.variable}`}>
                <div className="navbar">
                    <Link href="/" className="logo">
                        Forum
                    </Link>
                    <Link href="/list">List</Link>
                    {session ? (
                        <span>
                            {session.user.name} <LogoutBtn />
                        </span>
                    ) : (
                        <div>
                            <LoginBtn />
                            <SignupBtn />
                        </div>
                    )}
                </div>
                {children}
            </body>
        </html>
    );
}
